export enum ActionType {
    FETCH_PRODUCTS = "FETCH_PRODUCTS",
    FETCH_PRODUCT = "FETCH_PRODUCT",
    USER_LOADING = "USER_LOADING",
    USER_LOADED = "USER_LOADED",
    AUTH_ERROR = "AUTH_ERROR",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAIL = "LOGIN_FAIL",
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
    SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
    SIGNUP_FAIL = "SIGNUP_FAIL",
}
